#' Query TOAR database
#'
#' Submits the Query to the TOAR base and handles the response
#'
#' @param queryUrl a query url generated by \code{build_query}. string
#'
#' @export

query_toar_database = function(queryUrl){

  endpoint = stringr::str_remove(queryUrl,get_base_url()) |>
    stringr::word(1, sep = "/")

  response = httr::GET(queryUrl)

  if(httr::status_code(response) == 200){ #

  }

}
